name: Java CI with Maven

# this section defines when the workflow should run
on:
  push:
    branches:
      - master # Run this workflow on pushes to the main branch
    pull request:
      branches:
        - master

jobs:
  build:
    # The type of machine to run the job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        # Step to set up JDK 23 to run the java build
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step to build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step to run unit tests using Maven
      - name: Run Unit Tests
        run: mvn test